name: Config workflow

on:
  workflow_call:
    outputs:
      image_tag:
        description: "Docker image tag."
        value: ${{ jobs.config.outputs.image_tag }}
      image_repository:
        description: "Docker repository"
        value: ${{ jobs.config.outputs.image_repository }}
      image_name:
        description: "Docker image name."
        value: ${{ jobs.config.outputs.image_name }}

jobs:
  config:
    runs-on: self-hosted
    # Map the job outputs to step outputs
    outputs:
      image_tag: ${{ steps.generate_config.outputs.image_tag }}
      image_name: ${{ steps.generate_config.outputs.image_name }}
      image_repository: ${{ steps.generate_config.outputs.image_repository }}
    steps:
      - name: Generate Config
        id: generate_config
        run: |
          branch="$(echo ${{ github.ref }} | cut  -d '/' -f 3- | sed -e 's|/|-|g')"
          image_repository="$(echo ${{ github.repository }} | cut  -d '/' -f 2)"
          image_tag="${branch}-$(git describe --tag --always)"
          echo "::set-output name=image_tag::$image_tag"
          echo "::set-output name=image_repository::$image_repository"
          echo "::set-output name=image_name::$image_repository:$image_tag"
