name: test

on:
  workflow_dispatch:

jobs:
  generate_config:
    uses: ./.github/workflows/config.yml

  build:
    runs-on: ubuntu-latest
    needs: generate_config
    steps:
      - run: |
          echo ${{ needs.generate_config.outputs.image_tag }}
          echo ${{ needs.generate_config.outputs.image_name }}
          echo ${{ needs.generate_config.outputs.image_repository }}
