name: test

on:
  push:
    branch:
      - main
  workflow_dispatch:

env:
  SERVICE_NAME: $(echo ${{ github.repository }} | cut  -d '/' -f 2)
  BRANCH_NAME: $(echo ${{ github.ref }} | cut  -d '/' -f 3- | sed -e 's|/|-|g')

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Generate Config
        id: generate_config
        uses: ./.github/workflows/config.yml

      - name: Build
        run: |
          echo ${{ step.generate_config.outputs.image_tag }}
          echo ${{ step.generate_config.outputs.image_name }}
          echo ${{ step.generate_config.outputs.image_repository }}
