name: test

on:
  push:
    branch:
      - main
  workflow_dispatch:

env:
  SERVICE_NAME: $(echo ${{ github.repository }} | cut  -d '/' -f 2)
  BRANCH_NAME: $(echo ${{ github.ref }} | cut  -d '/' -f 3- | sed -e 's|/|-|g')

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ env.SERVICE_NAME }}
          echo ${{ env.BRANCH_NAME }}

  generate_config:
    uses: ./.github/workflows/config.yml

  build:
    runs-on: ubuntu-latest
    needs: generate_config
    steps:
      - run: |
          echo ${{ needs.generate_config.outputs.image_tag }}
          echo ${{ needs.generate_config.outputs.image_name }}
          echo ${{ needs.generate_config.outputs.image_repository }}
