name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  generate_config:
    uses: ./.github/workflows/config.yml
    with:
      service_name: github_ci

  build:
    runs-on: ubuntu-latest
    needs: generate_config
    steps:
      - run: |
          echo ${{ needs.generate_config.outputs.image_tag }}
          echo ${{ needs.generate_config.outputs.image_name }}
          echo ${{ needs.generate_config.outputs.image_repository }}
