name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

env:
  SERVICE_NAME: $(echo ${{ github.repository }} | cut  -d '/' -f 2)
  BRANCH_NAME: $(echo ${{ github.ref }} | cut  -d '/' -f 3- | sed -e 's|/|-|g')

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ env.SERVICE_NAME }}
          echo ${{ env.BRANCH_NAME }}
